### ISSUE TITLE
説明文が長いとTweetできない。

### ISSUE THREAD

**Issue by yosei** [yosei/singlesfan.com#7]
F, [2014-12-20T10:07:02.280275 #30450] FATAL -- : 
Twitter::Error::Forbidden (Status is over 140 characters.):
  app/controllers/events_controller.rb:119:in `tweet'
  app/controllers/events_controller.rb:65:in`block in create'
  app/controllers/events_controller.rb:63:in `create'

**Comment by yosei** [comment]
制限文字数を超えたらタイトルのみに削る？
